function [Gx,RF]=pleaseDelete(Nx,deltaK,readoutDuration)
sys = mr.opts('MaxGrad', 50, 'GradUnit', 'mT/m', ...
    'MaxSlew', 150, 'SlewUnit', 'T/m/s', ...
    'rfRingdownTime', 20e-6, 'rfDeadTime', 100e-6, ...
    'adcDeadTime', 0);
Gx = mr.makeTrapezoid('x','FlatArea',Nx * deltaK,'FlatTime',readoutDuration,'system',sys);
RF = mr.makeSincPulse(5*pi/180,'Duration',600.1e-6,...
                           'SliceThickness',1e-3,'apodization',0.5,...
                           'timeBwProduct',2,'system',sys); 
end